### PR TITLE
Enhanced libguard to add new interface

### PR DESCRIPTION
**Pull request by RameshIyyar**

### CODE REVIEW

**Comment by chiragsibm** [comment]
LGTM..

**Comment by ojayanth** [comment]
Code looks good.
Please include tested details for required commits. also it will be good to add test cases associated to new interfaces.

**Comment by RameshIyyar** [comment]
> Code looks good.
> Please include tested details for required commits. also it will be good to add test cases associated to new interfaces.

Sure, I will update the commit message and will add UT whereever is possible

**Comment by RameshIyyar** [comment]
> > Code looks good.
> > Please include tested details for required commits. also, it will be good to add test cases associated with new interfaces.
> 
> Sure, I will update the commit message and will add UT wherever is possible

@ojayanth @chiragsibm Updated all the patches with UT and commit message with test details.
Please review.

**Comment by chiragsibm** [comment]
LGTM..

**Review by ojayanth — APPROVED** [review]

**Pull request merged**
